import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod';

export const env = createEnv({
  client: {
    NEXT_PUBLIC_NODE_ENV: z.string().min(1),
    NEXT_PUBLIC_BASE_URL: z.string().min(1),
    NEXT_PUBLIC_SHOPIFY_DOMAIN: z.string().min(1),
    NEXT_PUBLIC_SHOPIFY_ACCESS_TOKEN: z.string().min(1),
    NEXT_PUBLIC_GRAPHQL_URI: z.string().min(1),
    NEXT_PUBLIC_SHOPIFY_ACCESS_TOKEN_ADMIN: z.string().min(1),
    NEXT_PUBLIC_GRAPHQL_URI_ADMIN: z.string().min(1),
    NEXT_PUBLIC_SANITY_STUDIO_ID: z.string().min(1),
    NEXT_PUBLIC_SANITY_STUDIO_DATASET: z.string().min(1),
    NEXT_PUBLIC_INSTAGRAM_ACCESS_TOKEN: z.string().min(1)
  },
  runtimeEnv: {
    NEXT_PUBLIC_NODE_ENV: process.env.NEXT_PUBLIC_NODE_ENV,
    NEXT_PUBLIC_BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
    NEXT_PUBLIC_SHOPIFY_DOMAIN: process.env.NEXT_PUBLIC_SHOPIFY_DOMAIN,
    NEXT_PUBLIC_SHOPIFY_ACCESS_TOKEN: process.env.NEXT_PUBLIC_SHOPIFY_ACCESS_TOKEN,
    NEXT_PUBLIC_GRAPHQL_URI: process.env.NEXT_PUBLIC_GRAPHQL_URI,
    NEXT_PUBLIC_SHOPIFY_ACCESS_TOKEN_ADMIN: process.env.NEXT_PUBLIC_SHOPIFY_ACCESS_TOKEN_ADMIN,
    NEXT_PUBLIC_GRAPHQL_URI_ADMIN: process.env.NEXT_PUBLIC_GRAPHQL_URI_ADMIN,
    NEXT_PUBLIC_SANITY_STUDIO_ID: process.env.NEXT_PUBLIC_SANITY_STUDIO_ID,
    NEXT_PUBLIC_SANITY_STUDIO_DATASET: process.env.NEXT_PUBLIC_SANITY_STUDIO_DATASET,
    NEXT_PUBLIC_INSTAGRAM_ACCESS_TOKEN: process.env.NEXT_PUBLIC_INSTAGRAM_ACCESS_TOKEN
  }
});
